stages:
  NAtl_925hPa_1hrLocalIntp_tozarr:
    cmd: python src/load_traj.py
    deps:
    - data/incoming/NAtl_Trajectories_Mid_Start_925hPa_1hrLocalInterp
    - src/load_traj.py
    outs:
    - data/converted/trajectory.zarr
  NAtl_925hPa_1hrLocalIntp_upload:
    cmd: python src/upload_swift.py
    deps:
    - data/converted/trajectory.zarr
    - src/upload_swift.py
